config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users
  root to: 'homes#top'
  get 'users/:id/favorites' => 'users#favorites', as: 'favorites'
  resources :plans, only: [:new, :create, :index, :show, :destroy] do
    resources :plan_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :plan
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
  has_many :plan_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/plan_comment.rb
class PlanComment < ApplicationRecord
  belongs_to :user
  belongs_to :plan
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plans, dependent: :destroy
  has_many :plan_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id"
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id"
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top]

  def after_sign_in_path_for(resource)
    plans_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i(show edit update destroy)

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :body, :start_date, :end_date)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    plan = Plan.find(params[:plan_id])
    favorite = current_user.favorites.new(plan_id: plan.id)
    favorite.save
    redirect_to plan_path(plan)
  end

  def destroy
    plan = Plan.find(params[:plan_id])
    favorite = current_user.favorites.find_by(plan_id: plan.id)
    favorite.destroy
    redirect_to plan_path(plan)
  end

  # def create
  #   favorite = Favorite.new(user_id: @current_user.id, plan_id: params[:plan_id])
  #   favorite.save
  #   redirect_to("/plans/#{params[:plan_id]}")
  # end

  # def destroy
  #   favorite = Favorite.find_by(user_id: @current_user.id, plan_id: params[:plan_id])
  #   favorite.destroy
  #   redirect_to("/plans/#{params[:plan_id]}")
  # end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    # render layout: false
  end
end

app/controllers/plan_comments_controller.rb
class PlanCommentsController < ApplicationController
  def create
    plan = Plan.find(params[:plan_id])
    # comment = current_user.plan_comments.new(plan_comment_params)
    comment = PlanComment.new(plan_params)
    comment.user_id = current_user.id
    comment.plan_id = plan.id
    comment.save
    redirect_to plan_path(plan)
  end

  def destroy
    PlanComment.find_by(id: params[:id], plan_id: params[:plan_id]).destroy
    redirect_to plan_path(params[:plan_id])
  end

  private

  def plan_params
    params.require(:plan_comment).permit(:comment)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id
    if @plan.save
      redirect_to plans_path
    else
      render :new
    end
  end

  def edit
  end

  def index
    @plan = Plan.all
    @new_plan = Plan.page(params[:page]).reverse_order
  end

  def show
    @plan = Plan.find(params[:id])
    @user = @plan.user
    @plan_comment = PlanComment.new
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    redirect_to plans_path
  end

  private

  def plan_params
    params.require(:plan).permit(:title, :content, :introduction, :name)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
    @user = user
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
    @user = user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @plan = @user.plans
    @favorites = Favorite.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def index
    @user = User.all
  end

  def favorites
    @user = User.find_by(id: params[:id])
    @favorites = Favorite.where(user_id: @user).all
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/plan_comments_helper.rb
module PlanCommentsHelper
end

app/helpers/plan_helper.rb
module PlanHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.body %></td>
        <td><%= event.start_date %></td>
        <td><%= event.end_date %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @event.body %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/favorites/index.html.erb
いいね一覧
<% if @favorites.present? %>
<% @favorites.each do |favorite| %>
<% plan = Plan.find_by(id: favorite.plan.id) %>
<%= attachment_image_tag plan.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
<%= link_to(plan.title, "/plans/#{plan.id}") %>
<%= plan.content %>
<%= link_to(plan.user.name, "/users/#{plan.user.id}") %>
<% end %>
<% else %>
<p>いいねはありません</p>
<% end %>

app/views/plans/index.html.erb
<div id="loading">
  <div id="loading_box">
    <div class="loading-one animation_loading">
      <p class="loading-txt">Now Loading...</p>
    </div>
  </div>
</div>

<div class="card-list-row  justify-content-between ">
<div class="plan-container offset-lg-2  px-0">
    <div class="row">新着記事一覧</div>
    <div class="d-flex flex-wrap">
    <% @new_plan.each do |plan| %>
<div class="card  shadow-lg mr-2 mb-2" style="width: 18rem;">
    <%= attachment_image_tag plan.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg",class:"card-img-top" %>
   <div class="card-body">
          　<p clas="card-name"><%= link_to user_path(plan.user) do %><%= plan.user.name %>先生</p><% end %>
         　 <p class="card-title"><%= link_to plan_path(plan.id) do %><%= plan.title %></p> <% end %>
　　　　　　<p class="card-text">内容:<%= plan.content %></p>
    </div>

</div>
<% end %>
</div>
<%= paginate @new_plan, theme: 'twitter-bootstrap-4' %>



<div>記事一覧</div>
<div class="d-flex flex-wrap">
<% @plan.each do |plan| %>
<div class="card  shadow-lg  mr-2 mb-2" style="width: 18rem;">
    <%= attachment_image_tag plan.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg",class:"card-img-top" %>
   <div class="card-body">


          　<p clas="card-name"><%= link_to user_path(plan.user) do %><%= plan.user.name %>先生</p><% end %>
         　 <p class="card-title"><%= link_to plan_path(plan.id) do %><%= plan.title %></p> <% end %>
　　　　　　<p class="card-text">内容:<%= plan.content %></p>

    </div>
</div>

<% end %>
  </div>
</div>
</div>
</div>

app/views/plans/new.html.erb
<h1>投稿フォーム</h1>
<% if @plan.errors.any? %>
  <%= @plan.errors.count %>件のエラーが発生しました
  <% @plan.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model: @plan,local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>内容</h4>
  <%= f.text_field :content %>
  <%= f.submit '投稿' %>
<% end %>

app/views/plans/show.html.erb
<div id="loading">
  <div id="loading_box">
    <div class="loading-one animation_loading">
      <p class="loading-txt">Now Loading...</p>
    </div>
  </div>
</div>

<div class="container ">
  <div class="row ">
    <div class="col ">

      <h3 class="profile-name"><%= @user.name %></h3>
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

  <p>タイトル：<%= @plan.title %></p>
  <p>内容：<%= @plan.content %></p>
  <p>ユーザーネーム：<%= @plan.user.name %></p>
  <p>投稿日時：<%= @plan.created_at.strftime('%Y/%m/%d') %></p>
  <% if @plan.user == current_user %>
    <%= link_to "削除", plan_path(@plan), method: :delete %>
  <% end %>

<% if @plan.favorited_by?(current_user) %>
    <p>
      <%= link_to plan_favorites_path(@plan), method: :delete do %>
        ♥<%= @plan.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to plan_favorites_path(@plan), method: :post do %>
        ♡<%= @plan.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>








<div>
<% @plan.plan_comments.each do |plan_comment| %>
  <%= plan_comment.user.name %>
  <%= plan_comment.comment %>

 <% if plan_comment.user == current_user %>
  <div>
    <%= link_to "削す", plan_plan_comment_path(plan_comment.plan, plan_comment), method: :delete %>
  </div>
  <% end %>

<% end %>
<div>
<%= form_with(model:[@plan, @plan_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>

 </div>
  </div>
</div>
</div>

app/views/relationships/_followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/_followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followers.html.erb
<h2><%= @user.name %>さんがフォロー中</h2>

<div class="followings-container">
<% if @users.exists? %>
<% @users.each do |user| %>
<div class="col-lg-8 mt-3 offset-lg-2 ">

  <div class="row">
	<div class="col-lg-3">
　　<%= link_to user_path(user) do %>
    <%= attachment_image_tag(user, :profile_image, :fill, 150, 200, fallback: "no_image.jpg") %>
  </div>

        <div class="col-lg-9">
        <h3><strong><%= user.name %></strong></h3><% end %>
        <hr></hr>
          <ul class="navbar-nav ml-auto">
        <li>フォロー数: <%= user.followings.count %>
        フォロワー数: <%= user.followers.count %></li>
        <hr></hr>
        <%=user.introduction %>
        </ul>

</div>
          </div>
            </div>
    <% end %>

<% else %>
  <p>ユーザーはいません</p>
<% end %>

              </div>

app/views/relationships/followings.html.erb
<h2><%= @user.name %>さんがフォロー中</h2>

<div class="followings-container">
<% if @users.exists? %>
<% @users.each do |user| %>
<div class="col-lg-8 mt-3 offset-lg-2 ">

  <div class="row">
	<div class="col-lg-3">
　　<%= link_to user_path(user) do %>
    <%= attachment_image_tag(user, :profile_image, :fill, 150, 200, fallback: "no_image.jpg") %>
  </div>

        <div class="col-lg-9">
        <h3><strong><%= user.name %></strong></h3><% end %>
        <hr></hr>
          <ul class="navbar-nav ml-auto">
        <li>フォロー数: <%= user.followings.count %>
        フォロワー数: <%= user.followers.count %></li>
        <hr></hr>
        <%=user.introduction %>
        </ul>

</div>
          </div>
            </div>
    <% end %>

<% else %>
  <p>ユーザーはいません</p>
<% end %>

              </div>

app/views/users/_info.html.erb
<div class="row">
	<div class="col-3 ">
  <%= attachment_image_tag(user, :profile_image, :fill, 150, 150, fallback: "no_image.jpg") %>
  </div>
  <div class="col-9">
  	<div class="row">
  		<div class="col-3">
	  <h2><%= user.name %></h2>
	  </div>
	  <div class="col-6">
	  <% if user == current_user %>
  <%= link_to 'プロフィール編集',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
    <% else %>
    <% if current_user.following?(user) %>
  <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete,class: "btn btn-outline-secondary btn-block" %>
<% else %>
  <%= link_to "フォロー", user_relationships_path(user.id), method: :post,class: "btn btn-outline-secondary btn-block" %>
<% end %>
  <% end %>
 </div>
 </div>
	  <div class="row">
	  	<div class="col-3 mt-2">投稿数<%= user.plans.count %>件</div>
	  	<div class="col-3  mt-2"><%= link_to user_followings_path(user) do %>フォロー数<%= user.followings.count %>人</div><% end %>
	  	<div class="col-3  mt-2"><%= link_to user_followers_path(user) do %>フォロワー数<%= user.followers.count %>人<% end %></div>
	  	<div class="col-3  mt-2"><%= link_to favorites_path do %>お気に入り<%= user.favorites.count %>件</div><% end %>
	  </div>
	  <div class="mt-2">
	  <%= user.introduction %>
	  </div>
  </div>
  </div>



<div class='row'>



</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>

  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  <label for='inputIntroduction'>Introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inpuIntroduction", placeholder:"自己紹介"  %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/favorites.html.erb
<div class="plan-list col-lg-8 offset-lg-2 ">
 <p>いいね一覧</p>
  <div class="row">
   <div class="d-flex flex-wrap">
    <% if @favorites.present? %>
     <% @favorites.each do |favorite| %>
      <% plan = Plan.find_by(id: favorite.plan.id) %>
      <%= attachment_image_tag plan.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
      <%= link_to(plan.title, "/plans/#{plan.id}") %>
      <%= plan.content %>
      <%= link_to(plan.user.name, "/users/#{plan.user.id}") %>
      <% end %>
    <% else %>
     <p>いいねはありません</p>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='row'>
   <div class="teacher-list-box col-4 offset-lg-2">
<%  @user.each do |user| %>
<%= link_to user_path(user.id) do%>
<div class="card px-0 shadow-lg col-3 style="width: 18rem;"">
   <%= attachment_image_tag user, :profile_image,:fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg",class:"card-img-top"; %>
   <div class="card-body">
      <div class="row">
     <%= user.name %>
  </div>
  </div>
  </div>
<% end %>


<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="profile-container px-2">
  <div class="col-lg-8 mt-3  offset-lg-2 ">
    <%= render 'info', user: @user %>
    <hr></hr>
  </div>

  <div class="plan-container ">

<div class="plan-list col-lg-8 offset-lg-2 ">
  <div class="row">
    <div class="d-flex flex-wrap">
  <% @plan.each do |plan| %>
<div class="card  shadow-lg  mr-2 mb-2" style="width: 18rem;">
   <div class="card-body">

  <p><%= link_to plan_path(plan.id), data: {"turbolinks" => false} do %><%= plan.title %></p> <% end %>
  <p><%= plan.content %></p>
</div>
</div>
<% end %>
</div>
</div>
</div>
</div>
</div>


<div id="calendar"></div><br>