config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users
  root to: 'homes#top'
  get 'users/:id/favorites' => 'users#favorites', as: 'favorites'
  resources :plans, only: [:new, :create, :index, :show, :destroy] do
    resources :plan_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :plan
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
  has_many :plan_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/plan_comment.rb
class PlanComment < ApplicationRecord
  belongs_to :user
  belongs_to :plan
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plans, dependent: :destroy
  has_many :plan_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id"
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id"
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i(show edit update destroy)

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :body, :start_date, :end_date)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    plan = Plan.find(params[:plan_id])
    favorite = current_user.favorites.new(plan_id: plan.id)
    favorite.save
    redirect_to plan_path(plan)
  end

  def destroy
    plan = Plan.find(params[:plan_id])
    favorite = current_user.favorites.find_by(plan_id: plan.id)
    favorite.destroy
    redirect_to plan_path(plan)
  end

  # def create
  #   favorite = Favorite.new(user_id: @current_user.id, plan_id: params[:plan_id])
  #   favorite.save
  #   redirect_to("/plans/#{params[:plan_id]}")
  # end

  # def destroy
  #   favorite = Favorite.find_by(user_id: @current_user.id, plan_id: params[:plan_id])
  #   favorite.destroy
  #   redirect_to("/plans/#{params[:plan_id]}")
  # end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    # render layout: false
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id
    if @plan.save
      redirect_to plans_path
    else
      render :new
    end
  end

  def edit
  end

  def index
    @plan = Plan.all
    @new_plan = Plan.page(params[:page]).reverse_order
  end

  def show
    @plan = Plan.find(params[:id])
    @user = @plan.user
    @plan_comment = PlanComment.new
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    redirect_to plans_path
  end

  private

  def plan_params
    params.require(:plan).permit(:title, :content, :introduction, :name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @plan = @user.plans
    @favorites = Favorite.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def index
    @user = User.all
  end

  def favorites
    @user = User.find_by(id: params[:id])
    @favorites = Favorite.where(user_id: @user).all
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/plan_comments_helper.rb
module PlanCommentsHelper
end

app/helpers/plan_helper.rb
module PlanHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight©︎ Ochikobore Karano Dakkyaku</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
 <header>

    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top ">

    <div class="container-fluid">
      <a class="navbar-brand">
        <%= link_to "Ochikobore" , root_path, data: {"turbolinks" => false} %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-dark" type="submit">Search</button>
    </form>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
 <% if user_signed_in? %>
    <li><%= link_to '講師一覧', users_path, class: 'nav-link text-dark fas fa-users', data: {"turbolinks" => false} %></li>
    <li><%= link_to '投稿一覧', plans_path ,class: 'nav-link text-dark fas fa-home', data: {"turbolinks" => false} %> </li>
    <li><%= link_to '投稿フォーム', new_plan_path,class: 'nav-link text-dark fas fa-plus-square', data: {"turbolinks" => false}  %></li>
    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'nav-link text-dark fas fa-sign-out-alt', data: {"turbolinks" => false}  %> </li>
    <li><%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark fas fa-user', data: {"turbolinks" => false} %></li>
    <li><div id="sp-menu">
      <h2>MENU</h2>
      <ul>
        <li><%= link_to "講師一覧", users_path, data: {"turbolinks" => false} %></li>
        <li><%= link_to "投稿一覧",plans_path , data: {"turbolinks" => false} %></li>
        <li><%= link_to '投稿フォーム', new_plan_path, data: {"turbolinks" => false}  %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: {"turbolinks" => false}  %></li>
        <li><%= link_to 'マイページ', user_path(current_user.id),  data: {"turbolinks" => false} %></li>
      </ul>
    </div>
    <div id="hm-icon">
      <a class="menu-trigger" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div></li>
    <% else %>
      <li> <%= link_to "新規登録", new_user_registration_path,class: 'fas fa-user-plus nav-link text-dark', data: {"turbolinks" => false} %></li>
      <li> <%= link_to "ログイン", new_user_session_path,class: 'fas fa-sign-in-alt nav-link text-dark' , data: {"turbolinks" => false}%></li>
    <% end %>
     </ul>
</header>

app/views/layouts/_menu.html.erb
  <div id="sp-menu">
      <h2>MENU</h2>
      <ul>
        <li><a href="#">MENU1</a></li>
        <li><a href="#">MENU2</a></li>
        <li><a href="#">MENU3</a></li>
        <li><a href="#">MENU4</a></li>
        <li><a href="#">MENU5</a></li>
      </ul>
    </div>

    <div id="hm-icon">
      <a class="menu-trigger" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag('favicon.ico') %>
    <title>Careerscram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="bg-light" data-turbolinks="false">
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>


    </body>
</html>